export const Module7=()=>{
    return(
        <div>
            <div>start</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
            <div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>Module7</div>
<div>stop</div>
</div>
        
    )
}